version: '3.8'

services:
  db:
    image: mysql:8.0.30
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
