version: '3.8'

services:
  db:
    image: mysql:8.0.30
    container_name: db-host
    environment:
      MYSQL_DATABASE: oceans
      MYSQL_USER: oceans
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf

  minio:
    build: ./docker/minio
    volumes:
      - ./docker/minio/data:/export
      - ./docker/minio/config:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
  createbuckets:
    container_name: oceans-createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 root password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/default;
      /usr/bin/mc policy download myminio/default;
      /usr/bin/mc policy set public myminio/default;
      exit 0;
      "
